apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://easyshop.letsdeployit.com/api"
  NEXTAUTH_URL: "https://easyshop.letsdeployit.com/"
  NEXTAUTH_SECRET: "1IsoIqXBI+s7uGovBg0zVsdHMMxdA0sXPkzeNBHzhKc="
  JWT_SECRET: "8d9d1657a7f70b4efb30fe2a37a0bf59a46b79808d510ee7f710f57131a6accc"