apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  NEXTAUTH_SECRET: "1IsoIqXBI+s7uGovBg0zVsdHMMxdA0sXPkzeNBHzhKc="
  JWT_SECRET: "8d9d1657a7f70b4efb30fe2a37a0bf59a46b79808d510ee7f710f57131a6accc"