apiVersion: batch/v1
kind: Job
metadata:
  name: easyshop-migration
  namespace: easyshop
spec:
  template:
    spec:
      containers:
        - name: migration
          image: devop715/easyshop-migration:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb-service:27017/easyshop
          restartPolicy: OnFailure